#!/bin/bash
/root/AQM/myred/queuedata/read.sh
cp queuedata_myred.txt /home/samba_shared_dir
/root/AQM/myred/iproute2-3.1.0/tc/tc qdisc del dev eth0 root
rmmod /root/AQM/myred/queuedata/seqfile_queuedata_myred.ko
rmmod /root/AQM/myred/modules/sch_myred.ko

